[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 't9md/vim-textmanip'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'scrooloose/vim-slumlord'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

##[[plugins]]
##repo = 'prabirshrestha/vim-lsp'
##depends = 'async.vim'
##
##[[plugins]]
##repo = 'prabirshrestha/async.vim'
##
##[[plugins]]
##repo = 'prabirshrestha/asyncomplete.vim'
##
##[[plugins]]
##repo = 'prabirshrestha/asyncomplete-lsp.vim'
##
##[[plugins]]
##repo = 'prabirshrestha/asyncomplete-buffer.vim'
##
##[[plugins]]
##repo = 'mattn/vim-lsp-settings'
##
##[[plugins]]
##repo = 'yami-beta/asyncomplete-omni.vim'

[[plugins]]
repo = 'chumakd/perlomni.vim'

[[plugins]]
repo = 'natebosch/vim-lsc'

[[plugins]]
repo = 'uarun/vim-protobuf'

[[plugins]]
repo = 'Shougo/vinarise.vim'

[[plugins]]
repo = 'mattn/vim-goaddtags'

[[plugins]]
repo = 'mattn/vim-goimpl'

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'sebdah/vim-delve'

[[plugins]]
repo = 'benmills/vimux'

[[plugins]]
repo = 'cespare/vim-go-templates'

[[plugins]]
repo = 'yko/mojo.vim'

[[plugins]]
repo = 'haya14busa/vim-auto-programming'

[[plugins]]
repo = 'google/vim-jsonnet'

[[plugins]]
repo = 'itkq/fluentd-vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = ':TSUpdate'

[[plugins]]
repo = 'sgur/vim-editorconfig'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'RutaTang/quicknote.nvim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'yuzoiwasaki/fluentd.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'uga-rosa/ddc-nvim-lsp-setup'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'

[[plugins]]
repo = 'Shougo/ddx.vim'

[[plugins]]
repo ='Shougo/ddu.vim'

[[plugins]]
repo ='Shougo/ddu-ui-ff'

[[plugins]]
repo ='Shougo/ddu-source-file_rec'

[[plugins]]
repo ='shun/ddu-source-rg'

[[plugins]]
repo ='Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo ='Shougo/ddu-kind-file'

[[plugins]]
repo = 'j-hui/fidget.nvim'

[[plugins]]
repo = 'monaqa/dial.nvim'

[[plugins]]
repo = 'uga-rosa/utf8.nvim'

[[plugins]]
repo = 'shellRaining/hlchunk.nvim'
