[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 't9md/vim-textmanip'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/vimfiler.vim'
[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'scrooloose/vim-slumlord'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'chumakd/perlomni.vim'

[[plugins]]
repo = 'natebosch/vim-lsc'

[[plugins]]
repo = 'uarun/vim-protobuf'

[[plugins]]
repo = 'Shougo/vinarise.vim'

[[plugins]]
repo = 'mattn/vim-goaddtags'

[[plugins]]
repo = 'mattn/vim-goimpl'

[[plugins]]
repo = 'jonsmithers/vim-html-template-literals'

[[plugins]]
repo = 'ziglang/zig.vim'

[[plugins]]
repo = 'jxnblk/vim-mdx-js'

[[plugins]]
repo = 'sago35/tinygo.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'evanleck/vim-svelte'

#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
#depends = 'async.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'uga-rosa/ddc-nvim-lsp-setup'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'

[[plugins]]
repo = 'matsui54/denops-signature_help'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
